#!/bin/env bash

podman run -ti --rm \
        -e DISPLAY=$DISPLAY \
        -e QT_X11_NO_MITSHM=1 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v ~/.aws/:/home/jenkins/.aws/ \
        -u root \
        --network host \
        --privileged \
        -v ${PWD}:/mnt/workspace \
        -w /mnt/workspace \
        ${CONTAINER} \
        bash
